/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seleuco_mame4droid_Emulator */

#ifndef _Included_com_seleuco_mame4droid_Emulator
#define _Included_com_seleuco_mame4droid_Emulator
#ifdef __cplusplus
extern "C" {
#endif
#undef com_seleuco_mame4droid_Emulator_FPS_SHOWED_KEY
#define com_seleuco_mame4droid_Emulator_FPS_SHOWED_KEY 1L
#undef com_seleuco_mame4droid_Emulator_EXIT_GAME_KEY
#define com_seleuco_mame4droid_Emulator_EXIT_GAME_KEY 2L
#undef com_seleuco_mame4droid_Emulator_INFOWARN_KEY
#define com_seleuco_mame4droid_Emulator_INFOWARN_KEY 8L
#undef com_seleuco_mame4droid_Emulator_EXIT_PAUSE
#define com_seleuco_mame4droid_Emulator_EXIT_PAUSE 9L
#undef com_seleuco_mame4droid_Emulator_IDLE_WAIT
#define com_seleuco_mame4droid_Emulator_IDLE_WAIT 10L
#undef com_seleuco_mame4droid_Emulator_PAUSE
#define com_seleuco_mame4droid_Emulator_PAUSE 11L
#undef com_seleuco_mame4droid_Emulator_FRAME_SKIP_VALUE
#define com_seleuco_mame4droid_Emulator_FRAME_SKIP_VALUE 12L
#undef com_seleuco_mame4droid_Emulator_SOUND_VALUE
#define com_seleuco_mame4droid_Emulator_SOUND_VALUE 13L
#undef com_seleuco_mame4droid_Emulator_THROTTLE
#define com_seleuco_mame4droid_Emulator_THROTTLE 14L
#undef com_seleuco_mame4droid_Emulator_CHEAT
#define com_seleuco_mame4droid_Emulator_CHEAT 15L
#undef com_seleuco_mame4droid_Emulator_AUTOSAVE
#define com_seleuco_mame4droid_Emulator_AUTOSAVE 16L
#undef com_seleuco_mame4droid_Emulator_SAVESTATE
#define com_seleuco_mame4droid_Emulator_SAVESTATE 17L
#undef com_seleuco_mame4droid_Emulator_LOADSTATE
#define com_seleuco_mame4droid_Emulator_LOADSTATE 18L
#undef com_seleuco_mame4droid_Emulator_IN_MENU
#define com_seleuco_mame4droid_Emulator_IN_MENU 19L
#undef com_seleuco_mame4droid_Emulator_EMU_RESOLUTION
#define com_seleuco_mame4droid_Emulator_EMU_RESOLUTION 20L
#undef com_seleuco_mame4droid_Emulator_FORCE_PXASPECT
#define com_seleuco_mame4droid_Emulator_FORCE_PXASPECT 21L
#undef com_seleuco_mame4droid_Emulator_THREADED_VIDEO
#define com_seleuco_mame4droid_Emulator_THREADED_VIDEO 22L
#undef com_seleuco_mame4droid_Emulator_DOUBLE_BUFFER
#define com_seleuco_mame4droid_Emulator_DOUBLE_BUFFER 23L
#undef com_seleuco_mame4droid_Emulator_PXASP1
#define com_seleuco_mame4droid_Emulator_PXASP1 24L
#undef com_seleuco_mame4droid_Emulator_NUMBTNS
#define com_seleuco_mame4droid_Emulator_NUMBTNS 25L
#undef com_seleuco_mame4droid_Emulator_NUMWAYS
#define com_seleuco_mame4droid_Emulator_NUMWAYS 26L
#undef com_seleuco_mame4droid_Emulator_FILTER_FAVORITES
#define com_seleuco_mame4droid_Emulator_FILTER_FAVORITES 27L
#undef com_seleuco_mame4droid_Emulator_RESET_FILTER
#define com_seleuco_mame4droid_Emulator_RESET_FILTER 28L
#undef com_seleuco_mame4droid_Emulator_LAST_GAME_SELECTED
#define com_seleuco_mame4droid_Emulator_LAST_GAME_SELECTED 29L
#undef com_seleuco_mame4droid_Emulator_EMU_SPEED
#define com_seleuco_mame4droid_Emulator_EMU_SPEED 30L
#undef com_seleuco_mame4droid_Emulator_AUTOFIRE
#define com_seleuco_mame4droid_Emulator_AUTOFIRE 31L
#undef com_seleuco_mame4droid_Emulator_VSYNC
#define com_seleuco_mame4droid_Emulator_VSYNC 32L
#undef com_seleuco_mame4droid_Emulator_HISCORE
#define com_seleuco_mame4droid_Emulator_HISCORE 33L
#undef com_seleuco_mame4droid_Emulator_VBEAN2X
#define com_seleuco_mame4droid_Emulator_VBEAN2X 34L
#undef com_seleuco_mame4droid_Emulator_VANTIALIAS
#define com_seleuco_mame4droid_Emulator_VANTIALIAS 35L
#undef com_seleuco_mame4droid_Emulator_VFLICKER
#define com_seleuco_mame4droid_Emulator_VFLICKER 36L
#undef com_seleuco_mame4droid_Emulator_FILTER_NUM_YEARS
#define com_seleuco_mame4droid_Emulator_FILTER_NUM_YEARS 37L
#undef com_seleuco_mame4droid_Emulator_FILTER_NUM_MANUFACTURERS
#define com_seleuco_mame4droid_Emulator_FILTER_NUM_MANUFACTURERS 38L
#undef com_seleuco_mame4droid_Emulator_FILTER_NUM_DRIVERS_SRC
#define com_seleuco_mame4droid_Emulator_FILTER_NUM_DRIVERS_SRC 39L
#undef com_seleuco_mame4droid_Emulator_FILTER_NUM_CATEGORIES
#define com_seleuco_mame4droid_Emulator_FILTER_NUM_CATEGORIES 40L
#undef com_seleuco_mame4droid_Emulator_FILTER_CLONES
#define com_seleuco_mame4droid_Emulator_FILTER_CLONES 41L
#undef com_seleuco_mame4droid_Emulator_FILTER_NOTWORKING
#define com_seleuco_mame4droid_Emulator_FILTER_NOTWORKING 42L
#undef com_seleuco_mame4droid_Emulator_FILTER_MANUFACTURER
#define com_seleuco_mame4droid_Emulator_FILTER_MANUFACTURER 43L
#undef com_seleuco_mame4droid_Emulator_FILTER_GTE_YEAR
#define com_seleuco_mame4droid_Emulator_FILTER_GTE_YEAR 44L
#undef com_seleuco_mame4droid_Emulator_FILTER_LTE_YEAR
#define com_seleuco_mame4droid_Emulator_FILTER_LTE_YEAR 45L
#undef com_seleuco_mame4droid_Emulator_FILTER_DRVSRC
#define com_seleuco_mame4droid_Emulator_FILTER_DRVSRC 46L
#undef com_seleuco_mame4droid_Emulator_FILTER_CATEGORY
#define com_seleuco_mame4droid_Emulator_FILTER_CATEGORY 47L
#undef com_seleuco_mame4droid_Emulator_SOUND_DEVICE_FRAMES
#define com_seleuco_mame4droid_Emulator_SOUND_DEVICE_FRAMES 48L
#undef com_seleuco_mame4droid_Emulator_SOUND_DEVICE_SR
#define com_seleuco_mame4droid_Emulator_SOUND_DEVICE_SR 49L
#undef com_seleuco_mame4droid_Emulator_SOUND_ENGINE
#define com_seleuco_mame4droid_Emulator_SOUND_ENGINE 50L
#undef com_seleuco_mame4droid_Emulator_EMU_AUTO_RESOLUTION
#define com_seleuco_mame4droid_Emulator_EMU_AUTO_RESOLUTION 51L
#undef com_seleuco_mame4droid_Emulator_IN_MAME
#define com_seleuco_mame4droid_Emulator_IN_MAME 52L
#undef com_seleuco_mame4droid_Emulator_FILTER_YEARS_ARRAY
#define com_seleuco_mame4droid_Emulator_FILTER_YEARS_ARRAY 0L
#undef com_seleuco_mame4droid_Emulator_FILTER_MANUFACTURERS_ARRAY
#define com_seleuco_mame4droid_Emulator_FILTER_MANUFACTURERS_ARRAY 1L
#undef com_seleuco_mame4droid_Emulator_FILTER_DRIVERS_SRC_ARRAY
#define com_seleuco_mame4droid_Emulator_FILTER_DRIVERS_SRC_ARRAY 2L
#undef com_seleuco_mame4droid_Emulator_FILTER_CATEGORIES_ARRAY
#define com_seleuco_mame4droid_Emulator_FILTER_CATEGORIES_ARRAY 3L
#undef com_seleuco_mame4droid_Emulator_FILTER_KEYWORD
#define com_seleuco_mame4droid_Emulator_FILTER_KEYWORD 4L
/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    runT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_runT
  (JNIEnv *, jclass);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    runVideoT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_runVideoT
  (JNIEnv *, jclass);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setPadData
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_setPadData
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setAnalogData
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_setAnalogData
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    getValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_seleuco_mame4droid_Emulator_getValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    getValueStr
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_seleuco_mame4droid_Emulator_getValueStr
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setValue
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_setValue
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setValueStr
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_setValueStr
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    netplayInit
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_seleuco_mame4droid_Emulator_netplayInit
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
